In [1]:
%run ".\internal_exam.ipynb"

In [14]:
df = read_excel_file(r"C:\Users\kassenov_r\OneDrive - AEO NIS\Рабочий стол\Monitoring-SOCH Regression\Monitoring_2023\Monitoring сельские школы (longitudinal data).xlsx")

In [15]:
schools = [
    'КГУ «Бестамакская средняя школа» Алгинского района Актюбинской области',
    'КГУ «Общеобразовательная школа имени Досова» с. Катарколь Бурабайского района Акмолинской области',
    'КГУ «Общеобразовательная школа № 5 города Ақсай» Бурлинского района ЗКО'
]

In [17]:
# def sliced + percent multiplied by 100
df = df.loc[df['school_ru'].isin(schools), ['test', 'school_ru', 'fio', 'grade', 'subject', 'percent']].rename(columns={'school_ru' : 'school', 'fio' : 'name'})
df['percent'] = df['percent'] * 100

In [27]:
df4 = df[df['grade'] == 4]
df8 = df[df['grade'] == 8]

In [18]:
grouped = df.groupby(['test', 'school', 'name', 'grade', 'subject'])['percent'].mean().reset_index().round(2)
grouped

,test,school,name,grade,subject,percent
0,RS0423,КГУ «Бестамакская средняя школа» Алгинского ра...,Абдрахман Абылай Асқарұлы,8,8BIOL,70.0
1,RS0423,КГУ «Бестамакская средняя школа» Алгинского ра...,Абдрахман Абылай Асқарұлы,8,8CHEM,75.0
2,RS0423,КГУ «Бестамакская средняя школа» Алгинского ра...,Абдрахман Абылай Асқарұлы,8,8ENFL,40.0
3,RS0423,КГУ «Бестамакская средняя школа» Алгинского ра...,Абдрахман Абылай Асқарұлы,8,8KZFL,85.0
4,RS0423,КГУ «Бестамакская средняя школа» Алгинского ра...,Абдрахман Абылай Асқарұлы,8,8MATH,75.0
...,...,...,...,...,...,...
3330,RS1122,КГУ «Общеобразовательная школа № 5 города Ақса...,Ғизат Бағдат Жеңісұлы,4,4KZFL,10.0
3331,RS1122,КГУ «Общеобразовательная школа № 5 города Ақса...,Ғизат Бағдат Жеңісұлы,4,4MATH,50.0
3332,RS1122,КГУ «Общеобразовательная школа № 5 города Ақса...,Ғизат Бағдат Жеңісұлы,4,4SCIE,30.0
3333,RS1122,КГУ «Общеобразовательная школа № 5 города Ақса...,Қуанышқызы Ғалия,4,4KZFL,15.0
3334,RS1122,КГУ «Общеобразовательная школа № 5 города Ақса...,Қуанышқызы Ғалия,4,4SCIE,40.0

In [19]:
west = df[(df['school'] == 'КГУ «Общеобразовательная школа № 5 города Ақсай» Бурлинского района ЗКО') & (df['test'] == 'RS0423')]
west

,test,school,name,grade,subject,percent
7,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Ваймер Роман Витальевич,8,8KZSL,25.0
8,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Чермошенцева Ксения Александровна,8,8KZSL,75.0
11,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Мұрат Суляйман Арманұлы,8,8KZSL,75.0
17,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Макатова Татьяна Витальевна,8,8KZSL,75.0
22,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Мансуров Абибулла Александрович,8,8KZSL,30.0
...,...,...,...,...,...,...
26482,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Избасарова Айлита Рашитовна,8,8RUFL,55.0
26495,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Махлеев Дмитрий Павлович,8,8RUFL,45.0
26624,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Нұрман Әмина Мұханқызы,8,8PHYS,35.0
26631,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Жумашева Сымбат Ерболовна,8,8ENFL,50.0
26652,RS0423,КГУ «Общеобразовательная школа № 5 города Ақса...,Акбасов Даниал Сагинжанович,4,4MATH,80.0